name: test_4traderx
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  hive_flutter: ^1.1.0
  another_flushbar: ^1.12.29
  dio: ^4.0.6
  provider: ^6.0.3
  global_configuration: ^2.0.0-nullsafety.1
  flutter_screenutil: ^5.0.1+2
  intl: ^0.17.0
  flutter_vibrate: ^1.3.0
  custom_line_indicator_bottom_navbar: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cfg/
